import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import { Container, Box } from "@mui/material";
import Banner from "@/components/banner";
import { data } from "@/assets/data";
import { COLORS } from "@/utils/global";
import Services from "@/components/services";
import { roboto } from "@/utils/fonts";
import About from "@/components/aboutus";
import Choose from "@/components/choose";
import Stats from "@/components/stats";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Flex it</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Banner sliderData={data.sliderImage} />
      </Box>
      <Box
        sx={{
          p: 5,
          backgroundColor: COLORS.DARKBLUE,
        }}
      >
        <Services />
        <Box sx={{ mt: 20 }}>
          <About />
        </Box>
        <Box sx={{ mt: 20 }}>
          <Choose />
        </Box>
      </Box>
      <Box>
        <Stats />
      </Box>
    </>
  );
}
